export const POKEMON_CONSTANTS = {
    BUY_POKEMON: 'BUY_POKEMON',
    RETURN_POKEMON: 'RETURN_POKEMON',

    FETCH_POKEMON_REQUEST: 'FETCH_POKEMON_REQUEST',
    FETCH_POKEMON_SUCCESS: 'FETCH_POKEMON_SUCCESS',
    FETCH_POKEMON_FAILURE: 'FETCH_POKEMON_FAILURE',
}